config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'company', to: 'pages#company'
  get 'friends', to: 'pages#friends'
  get 'vote', to: 'pages#vote'
  get 'portfolio', to: 'users#portfolio'
  get 'search_stocks', to: 'stocks#search'
  resources :user_stocks, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users,through: :user_stocks


  def self.new_from_lookup(ticker_symbol)
    begin
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    price = strip_commas(looked_up_stock.l)
    new(name: looked_up_stock.name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.last_price)
    rescue Exception => e
      return nil
    end

##

  def self.strip_commas(number)
    number.gsub(",", "")
  end
  end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :user_stocks
  has_many :stocks, through: :user_stocks
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def profile

  end
  def friends

  end

  def company

  end

  def vote

  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search

    if params[:stock].present?
      @stock = Stock.new_from_lookup(params[:stock])
      if @stock
        render 'users/portfolio'
      else flash[:danger] = 'You have entered an invalid symbol'
      redirect_to portfolio_path
      end
    else flash[:danger]= 'You have entered empty stock'

      redirect_to portfolio_path
      end


end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def portfolio

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Invest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Invest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path  %></li>
            <li><%= link_to "My Portfolio", portfolio_path  %></li>
            <li><%= link_to "Companies", company_path %></li>
            <li><%= link_to "Friends", friends_path %></li>
            <li><%= link_to "Vote", vote_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/company.html.erb
<h1>Company page</h1>
<%= link_to 'Home', root_path%>

app/views/pages/friends.html.erb
<h1>Friends page</h1>
<%= link_to 'Company', company_path%>

app/views/pages/home.html.erb
<h1>Home page</h1>
<%= link_to 'profile', profile_path%>



<head>
  <title>Datastore and Firebase Auth Example</title>
</head>
<%= link_to "logout", destroy_user_session_path, method: :delete %>
<body>

<h1 >Finally... Transparent Investing</h1>
<p>FinDem allows you to share and learn investing tips from people just like you</p>


<h2>Login info:</h2>

<h2>Share your investments and find out what your peers are investing in</h2>
<p >See how you rank</p>

<h2>Get ideas on what to invest in next</h2>

<h2>Chat about different topics  such as Cryptocurrency, Real Estate, Index Funds and more...</h2>
</body>

app/views/pages/profile.html.erb
<h1>Profile Page</h1>
<%= link_to 'friends', friends_path%>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="well results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html('<%= j (render 'users/result.html') %>')

app/views/users/portfolio.html.erb
<h1>My Portfolio </h1>
<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote:true, method: :get, id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock],
                           placeholder: "Stock ticker symbol", autofocus: true,
                           class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>

  <% end %>
  <% if @stock %>
    <div class="well results-block">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.last_price %>
    </div>
  <% end %>

</div>